title: Mi página
author: Jon Ander Pérez
email: jonanperez@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Bienvenidos a mi página.

# social links
twitter_username: tu-usuario-twitter # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username:  tu-usuario-github # NO incluyas el carácter @ character, ¡o la compilación fallará!

show_excerpts: true # cámbialo a false para eliminar los extractos de la página principal
theme: minima
